FROM ubuntu16.04:base

# Set the working directory to /app
WORKDIR /mandelbrot
WORKDIR /mandelbrot/local
WORKDIR /mandelbrot/mandelbrot-platform

# Copy the current directory contents into the container at /app
ADD $(pwd)/../ /mandelbrot/mandelbrot-platform

# Install any needed packages specified in requirements.txt
RUN $(pwd)/scripts/golang_install.sh
# RUN /mandelbrot/mandelbrot-platform/docker/scripts/golang_install.sh

# Make port 80 available to the world outside this container
EXPOSE 9090

# Volume map
VOLUME /mandelbrot/mandelbrot-platform

# Define environment variable
# ENV NAME World
RUN cd /mandelbrot/mandelbrot-platform
#RUN go build src/main.go

# Run app.py when the container launches
#CMD ["./main"]
