version: '3'
services:
  platform:
    build: .
    working_dir: /mandelbrot/mandelbrot-platform
    ports:
     - "9090:9090"
    volumes:
     - .:/mandelbrot/mandelbrot-platform
    links:
     - redis
  redis:
    image: redis
    ports:
     - "6379:6379"
